name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: 正しいディレクトリに移動
      run: cd /workspaces/Pokk2103.github.io

    - name: 依存関係のインストール
      run: npm install

    - name: アプリケーションを開始
      run: npm start
