name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # GitHubトークンを使う

    - name: 移動
      run: cd main
    
    - name: 依存関係のインストール
      run: npm install

    - name: アプリケーションを開始
      run: npm start
